### ISSUE TITLE
[New Feature] filters / dark mode

### ISSUE THREAD

**Issue by antonio-anguiano** [cse110-fa22-group14/cse110-fa22-group14#24]
### **filters and dark mode**
**prerequisite**
html structuring
**description**
implement different filter options
**Insert the steps to complete to fully implement this feature**
- [ ] step 1: all of the colors should be stored in variables instead of directly in the css (i.e. background-color= BACKGROUND_ instead of background-color=red" and stored in a seperate file 
- [x] step 2: create multiple color pallets in different files
- [x] step 3: create js event to swap between these filters
- [x] step 4: store the current filter in local storage
- [x] step 5: js should select the last filter from local storage upon opening the website
- **Resources**
Please put any relevant resources that can help resolve this issue here.

**Comment by GoldenStone929** [comment]
I have already edited html, and js file that allows user to change the background color, I can add the dark mode and some other features with a little bit of change
