### ISSUE TITLE
sorting function

### ISSUE THREAD

**Issue by antonio-anguiano** [cse110-fa22-group14/cse110-fa22-group14#27]
### **[sorting function]**
**prerequisite**
the html for the filter should be complete and the functions that load previews for cards as well as one that returns the array in a parsed format should already be made. the method we are using to store the cards should also be set in stone
**description**
insert the description of the problem here.
let users sort based on the following parameters: date created (default), price, rating, location, brew type/drink type.
this will not persist between website reloads.

**Insert the steps to complete to fully implement this feature**
- [x] step 1: add event to the sorting dropdown menu in html
- [x] step 2: get parsed input and then sort it based on what was selected
- [x] step 3: return parsed array

**Resources**
Please put any relevant resources that can help resolve this issue here.

**Comment by will-loves-coding82** [comment]
this will be marked as resolved but in the future make sure you link pull requests to your issues
