### ISSUE TITLE
Button for Deleting Coffee Cards

### ISSUE THREAD

**Issue by h4henry** [cse110-fa22-group14/cse110-fa22-group14#30]
- Create a trash can icon
- Decide a good position where to put the icon(Probably next to the share button)

**Comment by HHT1228** [comment]
- Remove card from gallery, **probably gonna need an identifier for each card to do this**.
- Remove card info from local storage

**Comment by HHT1228** [comment]
I pushed a branch to the repo called features/deleteButton. I implemented the back-end functionality, but bugs still exist. I will continue fixing it this weekend. I also modified the coffee card component to add an ugly button just for testing, so **be careful if you want to pull from this branch**.
