### ISSUE TITLE
Urgent Bug Fix for Edit Button

### ISSUE THREAD

**Issue by will-loves-coding82** [cse110-fa22-group14/cse110-fa22-group14#46]
**Logic Errors for Editing Button in features/editButtonV2**

- [x] Currently the console throws an error when assigning the value of an input field to null. The reason this happens is because the DOM doesn't recognize the value attribute since it apparently doesn't work unless the element you're referring to exists. 

- [x] Also another bug is that the form doesn't populate the card's data consistently. You can see its data if you click on it right after its creation but then it disappears for any attempts after that. The most likely theory is that the currentId is not updated properly

**Comment by will-loves-coding82** [comment]
- [] Currently the console throws an error when assigning the value of an input field to null. The reason this happens is because if the user doesn't end up providing info for a particular field, the coffee card object will store null for that attribute, flavor for example. 
- [] Also another bug is that the form doesn't populate the card's data consistently. You can see its data if you click on it right after its creation but then it disappears for any attempts after thatThe most likely theory is that the currentId is not updated properly

**Comment by hurl365** [comment]
These bugs have been resolved by the pull request from feature/editButtonV2 to main.
