### ISSUE TITLE
[New Feature] Add import and export coffeecard

### ISSUE THREAD

**Issue by ZhaoyuTina** [cse110-fa22-group14/cse110-fa22-group14#47]
### **[Add import and export coffeecard]**
**prerequisite**
Export needs ID figured out

**description**
Import coffee card (json file)
Export button that can export json.

**Insert the steps to complete to fully implement this feature**
- [x] import
- [x] obtain respective element in local storage
- [x] export

**Resources**
https://developer.mozilla.org/en-US/docs/Web/API/File_API/Using_files_from_web_applications

**Comment by hurl365** [comment]
Fixed by #71
