### ISSUE TITLE
[New Feature] Re-structure the functionality bar at the top (with import button)

### ISSUE THREAD

**Issue by HHT1228** [cse110-fa22-group14/cse110-fa22-group14#65]
### **Re-structure the functionality bar at the top**
**prerequisite**
Pull from import branch before start working on this issue

**description**
The functionality section at the top of the web page is messed up due to the import button. It requires restructure to make the title be at the center. The import button is also a "raw" HTML element without css styling, aka ugly.

**Insert the steps to complete to fully implement this feature**
- [ ] Restructure the functionality section to adapt to the import/upload element
- [ ] Style the upload button

**Resources**
NA

**Comment by will-loves-coding82** [comment]
I would like to help out on restyling the look of the page
